services:
  applio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
      - "7001-7010:7001-7010"
    container_name: anai-applio
    restart: always
    environment:
      - RUN_ENV=development
      - PYTHONUNBUFFERED=1
      - GRADIO_ROOT_PATH=/applio
      - RABBIT_URL=amqp://anai:ydVyM3KDkJ@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - JOB_INDEX_REDIS_URL=redis://redis:6379/2
      - RELEASE_VIEWER_BASE_URL=${RELEASE_VIEWER_BASE_URL:-http://localhost}
      - RELEASE_VIEWER_SHARED_LOGS=/app/logs
      - RELEASE_VIEWER_SHARED_MODELS=/app/rvc/models
      - RELEASE_VIEWER_SHARED_DATASETS=/app/assets/datasets
      - RELEASE_VIEWER_SHARED_AUDIOS=/app/assets/audios
    shm_size: "48gb"
    depends_on:
      - rabbitmq
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: anai-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=anai
      - RABBITMQ_DEFAULT_PASS=ydVyM3KDkJ
      - RABBITMQ_DEFAULT_VHOST=/
    #    ports:
    #      - "15672:15672" # 관리 UI (http://localhost:15672)
    #      - "5672:5672"   # AMQP
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  # port 6379 for redis
  redis:
    image: redis:7.4.7-alpine
    container_name: anai-redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data:
  applio_release_worktrees: