services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
      - --providers.swarm=true
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=app-network
      - --entrypoints.web.address=:80

      # SSE/스트리밍에서 프록시 타임아웃
      - --entrypoints.web.transport.respondingtimeouts.readtimeout=0
      - --entrypoints.web.transport.respondingtimeouts.idletimeout=0
    ports:
      - "6969:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  applio:
    image: 339712720989.dkr.ecr.ap-northeast-1.amazonaws.com/dev/anai-applio:latest
    environment:
      - RUN_ENV=development
    networks:
      - app-network
    volumes:
      - nfs_applio_logs:/app/logs
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.gpu == true
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: NVIDIA-GPU
                value: 2
      labels:
        - traefik.enable=true

        # Host 헤더로가 applio.catslandlady.net 인것만 허용
        - traefik.http.routers.applio.rule=Host(`applio.catslandlady.net`)
        - traefik.http.routers.applio.entrypoints=web

        # 컨테이너 내부 6969
        - traefik.http.services.applio.loadbalancer.server.port=6969

        # Sticky Session/쿠키 기반
        - traefik.http.services.applio.loadbalancer.sticky.cookie=true
        - traefik.http.services.applio.loadbalancer.sticky.cookie.name=applio_sticky
        - traefik.http.services.applio.loadbalancer.sticky.cookie.httpOnly=true
        - traefik.http.services.applio.loadbalancer.sticky.cookie.sameSite=lax
        - traefik.http.services.applio.loadbalancer.sticky.cookie.secure=false
    secrets:
      - source: aws_credentials
        target: /root/.aws/credentials
        mode: 0400
      - source: aws_config
        target: /root/.aws/config
        mode: 0400

networks:
  app-network:
    driver: overlay

volumes:
  nfs_applio_logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-applio/logs"

secrets:
  aws_credentials:
    external: true
  aws_config:
    external: true