services:
  applio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
      - "7001-7010:7001-7010"
    container_name: anai-applio
    restart: always
    environment:
      - RUN_ENV=development
      - PYTHONUNBUFFERED=1
      - GRADIO_ROOT_PATH=/applio
      - RABBIT_URL=amqp://anai:ydVyM3KDkJ@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - JOB_INDEX_REDIS_URL=redis://redis:6379/2
      - RELEASE_VIEWER_BASE_URL=${RELEASE_VIEWER_BASE_URL:-http://localhost}
      - RELEASE_VIEWER_SHARED_LOGS=/app/logs
      - RELEASE_VIEWER_SHARED_MODELS=/app/rvc/models
      - RELEASE_VIEWER_SHARED_DATASETS=/app/assets/datasets
      - RELEASE_VIEWER_SHARED_AUDIOS=/app/assets/audios
    volumes:
      - "${HOME}/.aws:/root/.aws:ro"
      - type: volume
        source: nfs_applio_logs
        target: /app/logs
      - type: volume
        source: nfs_applio_models
        target: /app/rvc/models
      - type: volume
        source: nfs_applio_datasets
        target: /app/assets/datasets
      - type: volume
        source: nfs_applio_audios
        target: /app/assets/audios
      - type: volume
        source: applio_release_worktrees
        target: /app/.release_worktrees
    shm_size: "48gb"
    depends_on:
      - rabbitmq
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: anai-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=anai
      - RABBITMQ_DEFAULT_PASS=ydVyM3KDkJ
      - RABBITMQ_DEFAULT_VHOST=/
    #    ports:
    #      - "15672:15672" # 관리 UI (http://localhost:15672)
    #      - "5672:5672"   # AMQP
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./configs/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  redis:
    image: redis:7.4.7-alpine
    container_name: anai-redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data:
  applio_release_worktrees:

  nfs_applio_logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-applio-production/logs"

  nfs_applio_models:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-applio-production/rvc/models"

  nfs_applio_datasets:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-applio-production/assets/datasets"

  nfs_applio_audios:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=211.233.64.121,rw,nolock,soft"
      device: ":/data/nfs/share/anai-applio-production/assets/audios"